#!/usr/bin/with-contenv sh

# Change dir to app root dir
if [ ! -z "$GUNICORN_APP_DIR" ]; then
    cd ${GUNICORN_APP_DIR}
fi

# Run gunicorn
if [ ! -z "$GUNICORN_CMD" ]; then
    exec ${GUNICORN_CMD}
fi

